config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root 'welcome#index'
  resources :home, only: :index

  resources :companies do
      resources :reminders
      resources :contacts
      resources :jobs
  end

  resources :jobs do
    resources :reminders
    resources :interviews
    resources :responses
  end

  resources :contacts, only: :index
  resources :jobs, only: :index
  resources :interviews, only: :index
  resources :feedbacks, only: [:new,:create]


  #one_steps is in development testing
  #   resources :one_steps, only:[:index,:new,:create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :find_interview, except: [:index,:new, :create]
  before_filter :find_job, except: [:index]
  # rescue_from ActiveRecord::RecordNotFound, with: :not_found

  def index
    @all_interviews = Interview.where(user_id:current_user.id).order_by
  end

  def new
    @interview = Interview.new
    @company = Company.find(@job.company_id)
  end

  def create
    @company = Company.find(@job.company_id)
    @interview = Interview.create(interview_params)
    if @interview.valid?
      redirect_to company_job_path(@company, @job), notice: "Interview on #{@interview.interview_date.strftime("%m/%d/%Y")} created."
    else
      @interview.interview_date = nil
      @interview.interview_time = nil
      render 'new', alert: "Interview could not be created."
    end
  end

  def show
    @company = Company.find(@job.company_id)
    if @interview.contact_id
      @contact = Contact.find(@interview.contact_id)
    end
  end

  def update
    @company = Company.find(@job.company_id)
    if @interview.update_attributes(interview_params)
      redirect_to company_job_path(@company,@job), notice: "Interview on #{@interview.interview_date.strftime("%m/%d/%Y")} updated."
    else
      render job_interview_path(@interview), alert: "Failed to Update."
    end
  end

  def destroy
    @interview.destroy
    flash[:notice]="Interview on #{@interview.interview_date.strftime("%m/%d/%Y")} deleted"
    @company = Company.find(@job.company_id)
    redirect_to company_job_path(@company, @job)
  end

  private

  def find_interview
    @interview = Interview.find(params[:id])
  end

  def find_job
    @job = Job.find(params[:job_id])
  end

  def interview_params
    params.require(:interview).permit(:interview_date, :interview_time, :notes, :job_id, :user_id, :contact_id)
  end

  def not_found
      session[:return_to]||= root_url
      redirect_to session[:return_to], flash: {alert: 'Problem finding a record, you might not be authorized.'}
  end

end

app/views/interviews/_edit.html.erb
<% content_for(:title, "Job Interview") %>

<%= render 'layouts/errors', object: @interview %>
<%= form_for(@interview, html: { class: 'form-horizontal' }, url: job_interview_path(@job, @interview)) do |f| %>

  <div class="form-group">
      <%= f.label "Interview Date", class: "col-xs-12 col-sm-2"%>
    <div class="col-xs-6 col-sm-3">
      <%= f.date_field :interview_date, :autofocus=>true, class: 'form-control' %>
    </div>
  </div>

    <div class="form-group">
        <%= f.label "Interview Time", class: "col-xs-12 col-sm-2"%>
      <div class="col-xs-6 col-sm-3">
        <%= f.time_field :interview_time, class: 'form-control' %>
      </div>
    </div>

  <div class="form-group">
    <%= f.label "Interview Notes", class: "col-xs-12 col-sm-2"%>
    <div class="col-xs-11 col-sm-9">
      <%= f.text_area :notes, class: 'form-control' %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>
  <%= f.hidden_field :job_id, :value => @job.id %>

  <div class="form-group">
      <%= f.label "Choose a Contact", class: "col-xs-12 col-sm-2"%>
    <div class="col-xs-3 col-sm-3">
      <%= f.collection_select :contact_id, @company.contacts, :id, :first_name, prompt: true, class: 'form-select' %>
    </div>
  </div>

 	<div class="form-group">
    <div class="col-sm-offset-2">
      <%= render 'layouts/submit', form_type: "Interview", object: @interview, f: f %>
    </div>
  </div>

<% end %>

app/views/interviews/_form.html.erb
<%= render 'layouts/errors', object: @interview %>

<%= form_for(@interview, html: { class: 'form-horizontal' }, url: job_interviews_path(@job, @interview)) do |f| %>
  <% if !@interview.interview_date %>
    <div class="form-group">
        <%= f.label "Date", class: "col-xs-12 col-sm-2"%>
      <div class="col-xs-6 col-sm-5">
        <%= f.date_field :interview_date, :autofocus=>true, class: 'form-control' %>
      </div>
    </div>
  <% end %>

<% if !@interview.interview_time %>
    <div class="form-group">
        <%= f.label "Time", class: "col-xs-12 col-sm-2"%>
      <div class="col-xs-6 col-sm-5">
        <%= f.time_field :interview_time, class: 'form-control' %>
      </div>
    </div>
  <% end %>

  <div class="form-group">
      <%= f.label "Notes", class: "col-xs-12 col-sm-2"%>
    <div class="col-xs-11 col-sm-9">
      <%= f.text_area :notes, size: "100%x8%", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
      <%= f.label "Contact", class: "col-xs-2 col-sm-2"%>
    <div class="col-xs-3 col-sm-3">
      <%= f.collection_select :contact_id, @company.contacts, :id, :first_name, prompt: true, class: 'form-select' %>
    </div>
  </div>

  <%= f.hidden_field :job_id, :value => @job.id %>
  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-9">
      <%= render 'layouts/submit', form_type: "Interview", object: @interview, f: f %>
    </div>
  </div>

<% end %>

app/views/interviews/index.html.erb
<% content_for(:title, "Job Interviews") %>

<div class="row index-head">
  <h2>Interviews List</h2>
</div>

<div class="row interviews-ul">
<ul class="fa-ul">
  <% @all_interviews.each do |interview| %>
    <% job = Job.find(interview.job_id) %>
    <li><p><%= link_to "Interview Date: #{interview.interview_date.strftime("%m/%d/%Y")} at #{interview.interview_time.strftime("%I:%M %p")}  |  Notes: #{interview.notes} ", job_interview_path(job, interview),title: "View interview on #{interview.interview_date.strftime("%m/%d/%Y")}" %></p></li>
  <% end %>
</ul>
</div>

app/views/interviews/new.html.erb
<% content_for(:title, "Job Interviews") %>

<div class="border-form-div">
  <h4>Enter interview details:</h4>
  <%= render 'form' %>
</div>

app/views/interviews/show.html.erb
<% content_for(:title, "Job Interviews") %>

<div class="row col-pads">
  <h4>Interview Details</h4>
  <p><b>Company: </b><%= link_to "#{@company.name}", company_path(@company),title:"View #{@company.name}" %></p>
  <p><b>Job: </b><%=link_to "#{@job.description}", job_path(@job),title:"View #{@job.description} Job Application" %></p>
  <p><b>Date Scheduled: </b><%= @interview.interview_date.strftime("%m/%d/%Y") %></p>
  <p><b>Time Scheduled: </b><%= @interview.interview_time.strftime("%I:%M %p") %></p>

  <p><b>Primary Contact: </b>
  <% if @contact %>
    <%= link_to "#{@contact.first_name} #{@contact.last_name}", company_contact_path(@company, @contact), title:"View #{@contact.first_name} #{@contact.last_name}" %>
  <% end %>
  </p>
  <p><b>Notes: </b><%=@interview.notes %></p>
  <br>
  <%= render 'edit' %>
</div>

<div class="row col-pads">
  <div class="show-edit-del">
    <%= link_to job_interview_path(@job,@interview), data: {method: :delete, confirm: "Are you sure you want to delete this interview for the #{@job.description} job?" }, title: "Delete this Interview" do %>
      <%= image_tag("trash-holiday.png") %>
      <p>Delete</p>
    <% end %>
  </div>
  <div class="show-edit-del">
  <%= link_to company_job_path(@company, @job),title:"Back to Job Page" do %>
    <%= image_tag("navigation.png") %>
     <p>Back</p>
  <% end %>
  </div>
</div>