config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root 'welcome#index'
  resources :home, only: :index

  resources :companies do
      resources :reminders
      resources :contacts
      resources :jobs
  end

  resources :jobs do
    resources :reminders
    resources :interviews
    resources :responses
  end

  resources :contacts, only: :index
  resources :jobs, only: :index
  resources :interviews, only: :index
  resources :feedbacks, only: [:new,:create]


  #one_steps is in development testing
  #   resources :one_steps, only:[:index,:new,:create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :authenticate_user!, except: [:index]
  
def index
  if current_user
    @companies = Company.where(user_id:current_user.id).by_name.recent(10)
    @interviews = Interview.where(user_id:current_user.id).order_by.recent(10)
    @jobs = Job.where(user_id:current_user.id).order_by.recent(10)
    @reminders = Reminder.where(user_id: current_user.id).recent(10)
  else
    @companies = []
    @interviews = []
    @jobs = []
    @reminders = []
  end

end

end

app/views/home/index.html.erb
<% content_for(:title, "The Jobseeker") %>

	<div class="row one-step">
	<h3><%= link_to "Create a company", companies_path, class: "enter-home-1", title: "Create New Company" %> to get started.. <span class="enter-home-2">then add jobs, contacts and interviews.</span></h3>
	</div> 

	<div class="row row-one">
		<div class="outer-box col-xs-12 col-sm-12 col-md-6">
			<div class="index-one">
				<h4><%= content_tag(:i,nil,class: 'fa-reminder fa fa-keyboard-o')%> Recent Job Applications:</h4>
					<% @jobs.each do |job| %>
						<% company = Company.find(job.company_id) %>
						<p><%= link_to company_job_path(company, job), class: "companies-all", title: "View Application for #{job.description}" do %>
								<%= job.description %>
			        	<%= render 'layouts/job_closed', object: job %>
			        <% end %>
						</p>
						<% end %>
			</div>
		</div>
		<div class="outer-box col-xs-12 col-sm-12 col-md-6">
			<div class="index-two">
				<h4><%= content_tag(:i,nil,class: 'fa-reminder fa fa-building')%>  Recent Companies: </h4>
					<% @companies.each do |company| %>
						<p><%= link_to "#{company.name}", company_path(company), class: "companies-all", title:"View #{company.name}" %></p>
					<% end %>
			</div>
		</div>
	</div>

	<div class="row row-two">
		<div class="outer-box col-xs-12 col-sm-12 col-md-6">
			<div class="index-three">
				<h4><%= content_tag(:i,nil,class: 'fa-reminder fa fa-comments')%> Upcoming Interviews:</h4>
					<% @interviews.each do |interview| %>
						<% job = Job.find(interview.job_id) %>
						<% if interview.interview_date >= DateTime.now %>
						<p><%= link_to "#{interview.interview_date.strftime("%A, %b %d")} - #{interview.interview_time.strftime("%I:%M %p")}", job_interview_path(job,interview), title: "View Interview on #{interview.interview_date.to_formatted_s(:short)}", class: "companies-all" %></p>
						<% end %>
					<% end -%>
			</div>
		</div>

		<div class="outer-box col-xs-12 col-sm-12 col-md-6">
			<div class="index-four">
				<h4><%= content_tag(:i,nil,class: 'fa-reminder fa fa-bell')%>  Reminders: </h4>
					<% @companies.each do |company| %>
						<% company.reminders.each do |reminder| %>
							<p><%= reminder.due_date.to_formatted_s(:short) %>:<%= link_to " #{company.name}: #{reminder.subject}", company_path(company), title:"View Reminder on #{reminder.due_date.to_formatted_s(:short)}" %></p>
						<% end %>
					<% end %>
			</div>
		</div>
	</div>