config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root 'welcome#index'
  resources :home, only: :index

  resources :companies do
      resources :reminders
      resources :contacts
      resources :jobs
  end

  resources :jobs do
    resources :reminders
    resources :interviews
    resources :responses
  end

  resources :contacts, only: :index
  resources :jobs, only: :index
  resources :interviews, only: :index
  resources :feedbacks, only: [:new,:create]


  #one_steps is in development testing
  #   resources :one_steps, only:[:index,:new,:create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/company.rb
class Company < ActiveRecord::Base

has_many :contacts, ->{ order("last_name ASC")}, dependent: :destroy
has_many :jobs, ->{ order("application_date DESC")}, dependent: :destroy
has_many :interviews, through: :jobs
has_many :responses, through: :jobs
belongs_to :user
belongs_to :one_step, inverse_of: :company
has_many :reminders, as: :rem

accepts_nested_attributes_for :contacts
accepts_nested_attributes_for :jobs

validates :name, presence: true

scope :by_name, ->{ order(:name) }
scope :recent, ->(max){ limit(max) }

before_save :style_text
before_save :external_link

private

  def style_text
    self.name = self.name.downcase.titleize
    self.url = self.url.downcase if self.url
  end

  def external_link
    if !self.url.include?("http://")
      self.url.insert(0,"http://")
    end
  end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
	before_filter :authenticate_user!
  before_filter :find_company, except: [:index, :new, :create]
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

	def index
		@companies = Company.where(user_id:current_user.id).by_name
	end

	def new
		@company = Company.new
	end

	def create
		@company = Company.create(company_params)
		if @company.valid?
      redirect_to companies_path, notice: "Company: #{@company.name} created."
	  else
	   	render 'new', alert: "Company could not be created."
	  end
	end

	def edit
	end

	def show
    
	end

	def update
    if @company.update_attributes(company_params)
			redirect_to company_path(@company), notice: "Company: #{@company.name} updated."
		else
			render 'edit', alert: "Failed to Update."
		end
	end

	def destroy
		@company.destroy
    flash[:notice]="Company: #{@company.name} deleted, including all its contacts and jobs."
   	redirect_to root_path
	end


  private
  def company_params
    params.require(:company).permit(:name, :url, :comments, :user_id)
  end

  def find_company
		@company = Company.find(params[:id])
  end

  def not_found
    session[:return_to]||= root_url
    redirect_to session[:return_to], flash: {alert: 'Problem finding company record, you might not be authorized.'}
  end

end

app/views/companies/_form.html.erb
<%= render 'layouts/errors', object: @company %>

<%= form_for(@company, html: { class: 'form-horizontal' }) do |f| %>
 	<div class="form-group">
    	<%= f.label "Name", class: "col-sm-2 control-label"%>
    <div class="col-sm-6">
    	<%= f.text_field :name, :autofocus=>true, class: 'form-control' %>
   	</div>
  </div>
 	<div class="form-group">
    	<%= f.label "Website", class: "col-sm-2 control-label"%>
    <div class="col-sm-6">
    	<%= f.text_field :url, placeholder: "Enter the website address",class: 'form-control' %>
   	</div>
  </div> 	<div class="form-group">
    	<%= f.label :"Comments", class: "col-sm-2 control-label"%>
    <div class="col-sm-6">
    	<%= f.text_area :comments, class: 'form-control' %>
   	</div>
  </div>

 <%= f.hidden_field :user_id, value: current_user.id %>

 	<div class="form-group">
	  <div class="col-sm-offset-2 col-sm-9">
      <%= render 'layouts/submit', form_type: "Company", object: @company, f: f %>
    </div>
 	</div>

<% end %>

app/views/companies/edit.html.erb
<% content_for(:title, "Companies") %>

<div class="border-form-div">
  <h4>Update Company Information:</h4>
  <%= render 'form' %>
</div>

app/views/companies/index.html.erb
<% content_for(:title, "Companies") %>

<div class="row col-pads">
	<h2>Companies
	<%= link_to new_company_path, class: "btn btn-adds", title: "Add a new Company" do %>
    <%= content_tag(:i,nil,class: 'fa fa-plus fa-2x')%>
    Add New
  <% end %></h2>
</div>

<div class="row companies-ul">
	<ul class="fa-ul">
	  <% @companies.all.each do |company| %>
	    <li>
        <%= link_to company_path(company), title: "View #{company.name}" do %>
          <%= company.name %>
          <% if company.reminders.count > 0 %>
            <%= content_tag(:i,nil,class: 'fa-reminder fa fa-bell')%> 
          <% end %>
        <% end %>
      </li>
	  <% end %>
	</ul>
</div>

app/views/companies/new.html.erb
<% content_for(:title, "Companies") %>

<div class="border-form-div">
	<h4>Enter Company Information:</h4>
	<%= render 'form' %>
</div>

app/views/companies/show.html.erb
<% content_for(:title, "Companies") %>

<div class="row show-header">
  <h2>Company: <span class="company-show-head"><%= @company.name %></h2></span>
</div>

<div class="col-xs-12 show-header show_bottom_line">
  <% if @company.reminders.count > 0 %>
    <h4>Important Reminder:</h4>
    <% @company.reminders.each do |reminder| %>
      <p><%= l reminder.due_date, format: :short %> - 
        <%= link_to "<i class='fa fa-reminder fa-bell'></i> #{reminder.subject}".html_safe, company_reminder_path(@company,reminder), title: "View This Reminder", alt: "View This Reminder" %>
        </p>
    <% end %>
  <% else %>
    <h4><%= link_to new_company_reminder_path(@company), title: "Create New Reminder", alt: "Create New Reminder" do %>
          <%= content_tag(:i,nil,class: 'fa-reminder fa fa-bell-slash')%>
          No reminders found - Create one
        <% end %></h4>
  <% end %>
</div>

<div class="col-xs-12 col-sm-4 show-bottom-line">
  <div class="row col-pads">
    <h4>Company Information:</h4>
    <p><b>Website Address: </b><%= link_to "#{@company.url}", @company.url, target: "_blank", title: "#{@company.url}", alt:"#{@company.url}" %></p>
    <% if @company.comments !="" %>
      <p><b>Notes: </b>  <%= @company.comments %></p>
    <% end %>
  </div>
  <div class="row margin-top">
    <div class="show-edit-del">
      <%= link_to edit_company_path(@company), title: "Edit Company Details", alt: "Edit Company Details" do %>
        <%= image_tag("edit.png") %>
        <p>Edit</p>
      <% end %>
    </div>
    <div class="show-edit-del">
      <%= link_to company_path(@company), data: {method: :delete, confirm: "WARNING! This will delete all contacts and interviews with #{@company.name}. Are you sure?" }, title: "Delete This Company", alt: "Delete This Company" do %>
        <%= image_tag("trash-holiday.png") %>
        <p>Delete</p>
      <% end %>
    </div>
    <div class="show-edit-del">
    <%= link_to root_path, title: "Home Page", alt: "Home Page" do %>
      <%= image_tag("navigation.png") %>
       <p>Home</p>
    <% end %>
    </div>
  </div>
</div>

<div class="col-xs-12 col-sm-4 show-bottom-line">
  <div class="row col-pads">
    <h3>Contacts 
      <%= link_to new_company_contact_path(@company), class: "btn btn-adds", title: "Add a New Contact", alt: "Add a New Contact" do %>
        <%= content_tag(:i,nil,class: 'fa fa-plus fa-2x')%> 
        Add New
      <% end %></h3>
    <p>Add all your contacts with this company. Add them to your responses or interviews to show who contacted you.</p>
  </div>

  <div class="row contacts-ul">
    <ul class="fa-ul">
      <% @company.contacts.each do |contact| %>
        <li><p><%= link_to "#{contact.first_name} #{contact.last_name}", company_contact_path(@company, contact), title: "View #{contact.first_name} #{contact.last_name}", alt: "View #{contact.first_name} #{contact.last_name}" %></p></li>
      <% end %>
    </ul>
  </div>
</div>

<div class="col-xs-12 col-sm-4">
  <div class="row col-pads">
    <h3>Applications 
      <%= link_to new_company_job_path(@company), class: "btn btn-adds", title: "Add a New Job Application", alt: "Add a New Job Application" do %>
        <%= content_tag(:i,nil,class: 'fa fa-plus fa-2x')%> 
        Add New
      <% end %></h3>
    <p>Enter any job applications sent in to this company. Then view the job to add responses and interviews.</p>
  </div>

  <div class="row jobs-ul">
    <ul class="fa-ul">
      <% @company.jobs.each do |job| %>
        <li><p>
          <%= link_to company_job_path(@company, job), title: "View #{job.description} application", alt: "View #{job.description} Application" do %>
            <%= job.description %>
            <%= render 'layouts/job_closed', object: job%>
          <% end %></p></li>
      <% end %>
    </ul>
  </div>
</div>