config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  root 'welcome#index'
  resources :home, only: :index

  resources :companies do
      resources :reminders
      resources :contacts
      resources :jobs
  end

  resources :jobs do
    resources :reminders
    resources :interviews
    resources :responses
  end

  resources :contacts, only: :index
  resources :jobs, only: :index
  resources :interviews, only: :index
  resources :feedbacks, only: [:new,:create]


  #one_steps is in development testing
  #   resources :one_steps, only:[:index,:new,:create]

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
    <div class="error_explanation">
      <h4><%= pluralize(object.errors.count, "error") %> prohibited this activity from being saved:</h4>

      <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

app/views/layouts/_job_closed.html.erb
<% if object.status == "Closed" %>
  <i class="fa fa-thumbs-down"> Closed</i>
<% end %>

app/views/layouts/_login.html.erb
<div class="auth-buttons">
  <% if user_signed_in? %>

    <div class="nav-format logged-in hidden-sm">
      <% if current_user.username %>
        Logged in as <strong><span class="logged-in-name"><%= current_user.username %></span></strong>.
      <% else %>
        Logged in as <strong><span class="logged-in-name"><%= current_user.email %></span></strong>.
      <% end %>
    </div>

    <div class="nav-format">
      <%= link_to '<i class="fa fa-pencil fa-fw"></i> Edit Profile'.html_safe, edit_user_registration_path, id: "edit-prof", class: "btn btn-default navbar-btn",title:"Edit Profile" %>
    </div>

    <div class="nav-format">
      <%= link_to '<i class="fa fa-sign-out fa-fw"></i> Log Out'.html_safe, destroy_user_session_path, :method=> :delete, id: "logout-prof", class: "btn btn-default navbar-btn",title:"Logout" %>
    </div>

  <% else %>
    <div class="nav-format">
      <%= link_to '<i class="fa fa-plus fa-fw"></i> Create Account'.html_safe, new_user_registration_path, id: "signup-prof", class: "btn btn-default navbar-btn",title:"Sign Up" %>
    </div>

    <div class="nav-format">
      <%= link_to '<i class="fa fa-sign-in fa-fw"></i> Log In'.html_safe, new_user_session_path, id: "login-prof", class: "btn btn-default navbar-btn",title:"Log In" %>
    </div>

    <div class="nav-format">
      <%= link_to '<i class="fa fa-home fa-fw"></i> Home'.html_safe, root_path, id: "home-page", class: "btn btn-default navbar-btn",title:"Home Page" %>
    </div>

  <% end %>
</div>

app/views/layouts/_submit.html.erb
<%= button_tag(type: "submit", class: "btn btn-default float-btn", title: f.object.new_record? ? "Create " + form_type : "Update " + form_type) do %>
  <i class="fa fa-plus-circle fa-fw"></i>
  <%= f.object.new_record? ? "Create " + form_type : "Update " + form_type %>
<% end %>
<%= link_to "<i class='fa fa-arrow-circle-left fa-fw'></i> Cancel".html_safe, :back, class: "btn btn-default float-btn",title:"Cancel" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
  <%= favicon_link_tag 'search.ico' %>
  <title><%= yield(:title) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<body class="container-fluid">
  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <div class="navbar-brand">
        <%= link_to image_tag("search.png", class: "brand-image") + ("<span class='job-seeker'>Job</span>Seeker".html_safe), root_path, title: "Home" %>
      </div>
    </div>
    <div class="collapse navbar-collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Companies", companies_path, title: "Manage your Companies" %></li>
        <li><%= link_to "Contacts", contacts_path, title: "View your Contacts" %></li>
        <li><%= link_to "Jobs", jobs_path, title: "View your jobs applied for" %></li>
        <li><%= link_to "Interviews", interviews_path, title: "View your Interviews" %></li>
        <li><%= link_to "Contact Us", new_feedback_path, title: "Submit Feedback or a Question" %></li>
      </ul>
      <div class="nav navbar-nav navbar-right">
        <%= render 'layouts/login' %>
      </div>
    </div>
  </nav>

  <div class="yield-box">
    <div id="flash" class="clearfix">
      <% if flash[:notice] != nil %>
        <div class='alert alert-success' role='alert'>
          <%= flash[:notice] %></div>
      <% end %>
      <% if flash[:alert] != nil %>
        <div class='alert alert-danger' role='alert'>
          <%= flash[:alert] %></div>
      <% end %>
    </div>
    <%= yield %>
  </div>

  <div class="navbar navbar-default navbar-fixed-bottom clearfix">
    <p id="copyright">Ruby on Rails application &copy; 2014 built by: <%= link_to "Visible Difference Web Development", "http://www.visible-difference.com", target: "_blank", title: "Visit www.visible-difference.com" %></p>
  </div>

</body>
</html>